import {
  User,
  Post,
  Application,
  Schedule,
  AttendanceReview,
} from '@/types/mockData';

export const mockUsers: User[] = [
  {
    id: 'admin-1',
    email: 'admin@staffjob.com',
    name: '관리자',
    role: 'admin',
    phone: '010-0000-0000',
    attendanceScore: 100,
    createdAt: '2024-01-01',
  },
  {
    id: 'manager-1',
    email: 'manager@company.com',
    name: '김매니저',
    role: 'manager',
    phone: '010-1111-1111',
    attendanceScore: 95,
    createdAt: '2024-02-01',
  },
  {
    id: 'member-1',
    email: 'worker1@email.com',
    name: '이알바',
    role: 'member',
    phone: '010-2222-2222',
    age: 25,
    gender: '남성',
    experience: '마라톤 행사 3회, 팝업스토어 5회',
    introduction: '성실하고 책임감 있게 일하겠습니다.',
    attendanceScore: 92,
    createdAt: '2024-03-01',
    documents: {
      idCard: true,
      bankbook: true,
      healthCertificate: true,
    },
  },
  {
    id: 'member-2',
    email: 'worker2@email.com',
    name: '박아르바이트',
    role: 'member',
    phone: '010-3333-3333',
    age: 23,
    gender: '여성',
    experience: '박람회 스탭 경험 2회',
    introduction: '밝은 성격으로 고객 응대에 자신 있습니다.',
    attendanceScore: 88,
    createdAt: '2024-03-15',
    documents: {
      idCard: true,
      bankbook: true,
    },
  },
];

export const mockPosts: Post[] = [
  // ========== 당일 스케줄 ==========

  // 1. 당일 예정 (오늘, 아직 시작 안함)
  {
    id: 'post-daily-upcoming',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[당일-예정] 저녁 이벤트 스탭',
    keywords: ['이벤트', '당일', '예정'],
    date: '2025-11-28',
    location: '강남구 코엑스',
    time: '18:00 - 22:00',
    salary: 100000,
    paymentDate: '당일 지급',
    preparation: '정장 착용',
    description: '오늘 저녁 이벤트 (아직 시작 전)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 5,
    currentApplicants: 3,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },

  // 2. 당일 진행중 (오늘, 현재 진행중)
  {
    id: 'post-daily-ongoing',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[당일-진행중] 오후 프로모션 스탭',
    keywords: ['프로모션', '당일', '진행중'],
    date: '2024-11-28',
    location: '신촌 현대백화점',
    time: '10:00 - 18:00',
    salary: 90000,
    paymentDate: '당일 지급',
    preparation: '편한 복장',
    description: '오후 프로모션 진행중 (10:00-18:00, 현재 14:00)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 8,
    currentApplicants: 8,
    createdAt: '2024-11-26',
    updatedAt: '2024-11-26',
  },

  // 3. 당일 완료 (오늘, 종료됨)
  {
    id: 'post-daily-completed-today',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'completed',
    title: '[당일-완료] 오전 행사 스탭',
    keywords: ['행사', '당일', '완료'],
    date: '2024-11-28',
    location: '여의도 IFC몰',
    time: '06:00 - 12:00',
    salary: 80000,
    paymentDate: '지급 완료',
    preparation: '운동복',
    description: '오전 행사 종료 (06:00-12:00, 현재 14:00)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 10,
    currentApplicants: 10,
    createdAt: '2024-11-27',
    updatedAt: '2024-11-28',
  },

  // 4. 당일 완료 (어제)
  {
    id: 'post-daily-completed-past',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'completed',
    title: '[당일-완료] 어제 행사 스탭',
    keywords: ['행사', '완료', '과거'],
    date: '2025-11-27',
    location: '홍대입구역',
    time: '14:00 - 20:00',
    salary: 95000,
    paymentDate: '지급 완료',
    preparation: '페스티벌 제공 유니폼',
    description: '어제 행사 완료',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 12,
    currentApplicants: 12,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-28',
  },

  // ========== 기간 스케줄 (~) ==========

  // 5. 기간 예정 (미래 기간)
  {
    id: 'post-range-upcoming',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[기간-예정] 연말 박람회 스탭',
    keywords: ['박람회', '기간', '예정'],
    date: '2025-12-15~2025-12-20',
    location: '코엑스',
    time: '09:00 - 18:00',
    salary: 100000,
    paymentDate: '주간 지급',
    preparation: '정장',
    description: '연말 박람회 기간 스탭 (미래)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 20,
    currentApplicants: 15,
    createdAt: '2024-11-20',
    updatedAt: '2024-11-20',
  },

  // 6. 기간 진행중 (오늘 포함)
  {
    id: 'post-range-ongoing',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[기간-진행중] 추수감사절 프로모션',
    keywords: ['프로모션', '기간', '진행중'],
    date: '2025-11-25~2025-11-30',
    location: '강남 일대',
    time: '10:00 - 20:00',
    salary: 95000,
    paymentDate: '일일 정산',
    preparation: '브랜드 유니폼 제공',
    description: '추수감사절 주간 프로모션 (현재 진행중)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 15,
    currentApplicants: 15,
    createdAt: '2024-11-18',
    updatedAt: '2024-11-18',
  },

  // 7. 기간 완료 (과거 기간)
  {
    id: 'post-range-completed',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'completed',
    title: '[기간-완료] 할로윈 페스티벌 스탭',
    keywords: ['페스티벌', '기간', '완료'],
    date: '2025-10-28~2025-11-03',
    location: '이태원 일대',
    time: '18:00 - 24:00',
    salary: 120000,
    paymentDate: '지급 완료',
    preparation: '페스티벌 복장',
    description: '할로윈 주간 페스티벌 (완료)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 30,
    currentApplicants: 30,
    createdAt: '2024-10-15',
    updatedAt: '2024-11-05',
  },

  // ========== 불연속 날짜 (,) ==========

  // 8. 불연속 예정 (모두 미래)
  {
    id: 'post-multiple-upcoming',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[불연속-예정] 주말 이벤트 스탭',
    keywords: ['이벤트', '주말', '예정'],
    date: '2025-12-07, 2025-12-08, 2025-12-14, 2025-12-15',
    location: '신촌 현대백화점',
    time: '11:00 - 19:00',
    salary: 90000,
    paymentDate: '당일 지급',
    preparation: '편한 복장',
    description: '12월 주말 이벤트 (모두 미래)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 6,
    currentApplicants: 4,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },

  // 9. 불연속 예정 (과거+미래 섞임)
  {
    id: 'post-multiple-upcoming-mixed',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[불연속-예정] 플래시 세일 프로모션',
    keywords: ['프로모션', '세일', '예정'],
    date: '2025-11-20, 2025-11-25, 2025-12-01, 2025-12-05',
    location: '강남 가로수길',
    time: '10:00 - 18:00',
    salary: 85000,
    paymentDate: '당일 지급',
    preparation: '단정한 복장',
    description: '플래시 세일 (과거+미래 날짜 섞임, 미래 남음)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 8,
    currentApplicants: 6,
    createdAt: '2024-11-15',
    updatedAt: '2024-11-15',
  },

  // 10. 불연속 진행중 (오늘 포함, 미래 없음)
  {
    id: 'post-multiple-ongoing',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[불연속-진행중] 특별 프로모션',
    keywords: ['프로모션', '특별', '진행중'],
    date: '2025-11-25, 2025-11-26, 2025-11-28',
    location: '명동 메인거리',
    time: '12:00 - 20:00',
    salary: 100000,
    paymentDate: '당일 지급',
    preparation: '브랜드 유니폼 제공',
    description: '특별 프로모션 (오늘 포함, 미래 없음)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 10,
    currentApplicants: 10,
    createdAt: '2024-11-20',
    updatedAt: '2024-11-20',
  },

  // 11. 불연속 완료 (모두 과거)
  {
    id: 'post-multiple-completed',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'completed',
    title: '[불연속-완료] 블랙프라이데이 세일',
    keywords: ['세일', '블랙프라이데이', '완료'],
    date: '2025-11-22, 2025-11-23, 2025-11-24',
    location: '명동 쇼핑거리',
    time: '09:00 - 22:00',
    salary: 150000,
    paymentDate: '지급 완료',
    preparation: '세일 유니폼 제공',
    description: '블랙프라이데이 주말 세일 (완료)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 25,
    currentApplicants: 25,
    createdAt: '2024-11-10',
    updatedAt: '2024-11-25',
  },

  // ========== 겹치는 스케줄 ==========

  // 12-14. 오늘 같은 시간대 겹침 (당일)
  {
    id: 'post-overlap-1',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침1] 오늘 아침 마라톤 대회',
    keywords: ['마라톤', '행사', '겹침'],
    date: '2025-11-28',
    location: '잠실종합운동장',
    time: '06:00 - 12:00',
    salary: 80000,
    paymentDate: '당일 지급',
    preparation: '편한 운동화, 운동복',
    description: '마라톤 대회 스탭',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 15,
    currentApplicants: 15,
    createdAt: '2024-11-20',
    updatedAt: '2024-11-20',
  },
  {
    id: 'post-overlap-2',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침2] 오늘 아침 자선 행사',
    keywords: ['자선', '행사', '겹침'],
    date: '2025-11-28',
    location: '한강공원',
    time: '07:00 - 13:00',
    salary: 85000,
    paymentDate: '당일 지급',
    preparation: '자선 행사 티셔츠 제공',
    description: '자선 행사 스탭',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 10,
    currentApplicants: 10,
    createdAt: '2024-11-21',
    updatedAt: '2024-11-21',
  },
  {
    id: 'post-overlap-3',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침3] 오늘 오후 박람회',
    keywords: ['박람회', '전시', '겹침'],
    date: '2025-11-28',
    location: 'COEX',
    time: '13:00 - 19:00',
    salary: 90000,
    paymentDate: '당일 지급',
    preparation: '정장 착용',
    description: '박람회 안내 스탭',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 12,
    currentApplicants: 10,
    createdAt: '2024-11-22',
    updatedAt: '2024-11-22',
  },

  // 15-17. 12월 15일 겹침 (기간+불연속+당일)
  {
    id: 'post-overlap-future-1',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침4] 크리스마스 준비 행사',
    keywords: ['크리스마스', '준비', '겹침'],
    date: '2025-12-15',
    location: '명동 거리',
    time: '10:00 - 18:00',
    salary: 100000,
    paymentDate: '당일 지급',
    preparation: '크리스마스 복장',
    description: '크리스마스 준비 행사 (당일)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 20,
    currentApplicants: 15,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },
  {
    id: 'post-overlap-future-2',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침5] 연말 정산 박람회',
    keywords: ['박람회', '연말', '겹침'],
    date: '2025-12-10, 2025-12-15, 2025-12-20',
    location: 'COEX',
    time: '09:00 - 17:00',
    salary: 95000,
    paymentDate: '당일 지급',
    preparation: '정장',
    description: '연말 정산 박람회 (불연속)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 15,
    currentApplicants: 12,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },
  {
    id: 'post-overlap-future-3',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침6] 겨울 축제',
    keywords: ['축제', '겨울', '겹침'],
    date: '2025-12-13~2025-12-17',
    location: '잠실 롯데월드',
    time: '11:00 - 20:00',
    salary: 110000,
    paymentDate: '주간 지급',
    preparation: '축제 유니폼 제공',
    description: '겨울 축제 기간 스탭 (기간)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 25,
    currentApplicants: 20,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },

  // ========== 엣지 케이스 ==========

  // 18. 내일 스케줄 (예정)
  {
    id: 'post-tomorrow',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[내일] 쇼핑몰 오픈 행사',
    keywords: ['오픈', '쇼핑몰', '내일'],
    date: '2025-11-29',
    location: '강남역 지하쇼핑몰',
    time: '10:00 - 18:00',
    salary: 90000,
    paymentDate: '당일 지급',
    preparation: '쇼핑몰 유니폼 제공',
    description: '쇼핑몰 오픈 행사 (내일)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 8,
    currentApplicants: 5,
    createdAt: '2024-11-27',
    updatedAt: '2024-11-27',
  },

  // 19. 한 달 후 (예정)
  {
    id: 'post-next-month',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[한달후] 신년 행사 준비',
    keywords: ['신년', '행사', '예정'],
    date: '2025-12-28',
    location: '여의도 공원',
    time: '14:00 - 22:00',
    salary: 150000,
    paymentDate: '당일 지급',
    preparation: '신년 행사 복장',
    description: '신년 행사 준비 (한 달 후)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 30,
    currentApplicants: 10,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },
];

export const mockApplications: Application[] = [
  {
    id: 'app-1',
    postId: 'post-1',
    applicantId: 'member-1',
    applicantName: '이알바',
    status: 'accepted',
    appliedAt: '2024-11-21',
    message: '마라톤 행사 경험 있습니다. 열심히 하겠습니다!',
  },
  {
    id: 'app-2',
    postId: 'post-1',
    applicantId: 'member-2',
    applicantName: '박아르바이트',
    status: 'pending',
    appliedAt: '2024-11-22',
    message: '성실히 임하겠습니다.',
  },
  {
    id: 'app-3',
    postId: 'post-2',
    applicantId: 'member-1',
    applicantName: '이알바',
    status: 'pending',
    appliedAt: '2024-11-23',
    message: '팝업스토어 경험 많습니다.',
  },
];

export const mockSchedules: Schedule[] = [
  {
    id: 'sch-1',
    userId: 'member-1',
    postId: 'post-4',
    title: '홍대 페스티벌 스탭',
    date: '2024-11-10',
    salary: 110000,
    paid: true,
  },
  {
    id: 'sch-2',
    userId: 'member-1',
    postId: 'post-1',
    title: '서울 마라톤 대회 스탭',
    date: '2024-12-15',
    salary: 120000,
    paid: false,
  },
];

export const mockAttendanceReviews: AttendanceReview[] = [
  {
    id: 'rev-1',
    postId: 'post-4',
    userId: 'member-1',
    score: 95,
    comment: '성실하고 책임감 있게 근무했습니다.',
    reviewedBy: 'manager-1',
    createdAt: '2024-11-11',
  },
  {
    id: 'rev-2',
    postId: 'post-4',
    userId: 'member-2',
    score: 85,
    comment: '전반적으로 양호하나 지각이 있었습니다.',
    reviewedBy: 'manager-1',
    createdAt: '2024-11-11',
  },
];

// Mock 로그인 함수
export function mockLogin(email: string, password: string): User | null {
  const user = mockUsers.find((u) => u.email === email);
  if (user && password === 'password123') {
    return user;
  }
  return null;
}

// Mock 회원가입 함수
export function mockSignup(
  email: string,
  password: string,
  name: string,
  role: 'member' | 'manager'
): User {
  const newUser: User = {
    id: `user-${Date.now()}`,
    email,
    name,
    role: role === 'manager' ? 'member' : role, // 매니저는 관리자 승인 필요
    attendanceScore: 100,
    createdAt: new Date().toISOString(),
  };
  mockUsers.push(newUser);
  return newUser;
}
