import {
  User,
  Post,
  Application,
  AttendanceReview,
  Schedule,
} from '@/types/mockData';

export const mockUsers: User[] = [
  {
    id: 'admin-1',
    email: 'admin@staffjob.com',
    name: '관리자',
    role: 'admin',
    phone: '010-0000-0000',
    kakaoId: 'admin_staff',
    photo: '/images/default-avatar.png',
    attendanceScore: 100,
    createdAt: '2024-01-01',
  },
  {
    id: 'manager-1',
    email: 'manager@company.com',
    name: '김매니저',
    role: 'manager',
    phone: '010-1111-1111',
    kakaoId: 'manager_kim',
    photo: '/images/manager-avatar.png',
    companyName: '(주)이벤트플러스',
    attendanceScore: 95,
    createdAt: '2024-02-01',
  },
  {
    id: 'member-1',
    email: 'worker1@email.com',
    name: '이서연',
    role: 'member',
    phone: '010-2222-2222',
    kakaoId: 'seoyeon_lee',
    photo: '/images/member1-avatar.png',
    birthDate: '1999-03-15',
    age: 25,
    gender: '여성',
    height: 165,
    weight: 52,
    personality: '밝고 긍정적이며 적극적인 성격입니다.',
    features: '친화력이 좋고 고객 응대에 능숙합니다.',
    experience: '마라톤 행사 3회, 팝업스토어 5회, 박람회 안내 2회',
    introduction: '성실하고 책임감 있게 일하겠습니다. 행사 경험이 풍부합니다.',
    attendanceScore: 92,
    createdAt: '2024-03-01',
    documents: {
      idCard: '/uploads/member1-idcard.jpg',
      bankbook: '/uploads/member1-bankbook.jpg',
      healthCertificate: '/uploads/member1-health.jpg',
      certificates: ['바리스타 2급', '컴퓨터활용능력 2급'],
      language: ['영어(중급)', '일본어(초급)'],
    },
  },
  {
    id: 'member-2',
    email: 'worker2@email.com',
    name: '김민준',
    role: 'member',
    phone: '010-3333-3333',
    kakaoId: 'minjun_kim',
    photo: '/images/member2-avatar.png',
    birthDate: '2001-07-20',
    age: 23,
    gender: '남성',
    height: 178,
    weight: 70,
    personality: '성실하고 책임감이 강합니다.',
    features: '체력이 좋고 장시간 근무 가능합니다.',
    experience: '박람회 스탭 경험 2회, 프로모션 행사 4회',
    introduction: '밝은 성격으로 고객 응대에 자신 있습니다.',
    attendanceScore: 88,
    createdAt: '2024-03-15',
    documents: {
      idCard: '/uploads/member2-idcard.jpg',
      bankbook: '/uploads/member2-bankbook.jpg',
      driverLicense: '/uploads/member2-license.jpg',
      language: ['영어(초급)'],
    },
  },
];

export const mockPosts: Post[] = [
  // ========== 당일 스케줄 ==========

  // 1. 당일 예정 (오늘, 아직 시작 안함)
  {
    id: 'post-daily-upcoming',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[당일-예정] 저녁 이벤트 스탭',
    keywords: ['이벤트', '당일', '예정'],
    date: '2025-11-28',
    location: '강남구 코엑스',
    time: '18:00 - 22:00',
    salary: 100000,
    paymentDate: '당일 지급',
    preparation: '정장 착용',
    description: '오늘 저녁 이벤트 (아직 시작 전)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 5,
    currentApplicants: 3,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },

  // 2. 당일 진행중 (오늘, 현재 진행중)
  {
    id: 'post-daily-ongoing',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[당일-진행중] 오후 프로모션 스탭',
    keywords: ['프로모션', '당일', '진행중'],
    date: '2024-11-28',
    location: '신촌 현대백화점',
    time: '10:00 - 18:00',
    salary: 90000,
    paymentDate: '당일 지급',
    preparation: '편한 복장',
    description: '오후 프로모션 진행중 (10:00-18:00, 현재 14:00)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 8,
    currentApplicants: 8,
    createdAt: '2024-11-26',
    updatedAt: '2024-11-26',
  },

  // 3. 당일 완료 (오늘, 종료됨)
  {
    id: 'post-daily-completed-today',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'completed',
    title: '[당일-완료] 오전 행사 스탭',
    keywords: ['행사', '당일', '완료'],
    date: '2024-11-28',
    location: '여의도 IFC몰',
    time: '06:00 - 12:00',
    salary: 80000,
    paymentDate: '지급 완료',
    preparation: '운동복',
    description: '오전 행사 종료 (06:00-12:00, 현재 14:00)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 10,
    currentApplicants: 10,
    createdAt: '2024-11-27',
    updatedAt: '2024-11-28',
  },

  // 4. 당일 완료 (어제)
  {
    id: 'post-daily-completed-past',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'completed',
    title: '[당일-완료] 어제 행사 스탭',
    keywords: ['행사', '완료', '과거'],
    date: '2025-11-27',
    location: '홍대입구역',
    time: '14:00 - 20:00',
    salary: 95000,
    paymentDate: '지급 완료',
    preparation: '페스티벌 제공 유니폼',
    description: '어제 행사 완료',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 12,
    currentApplicants: 12,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-28',
  },

  // ========== 기간 스케줄 (~) ==========

  // 5. 기간 예정 (미래 기간)
  {
    id: 'post-range-upcoming',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[기간-예정] 연말 박람회 스탭',
    keywords: ['박람회', '기간', '예정'],
    date: '2025-12-15~2025-12-20',
    location: '코엑스',
    time: '09:00 - 18:00',
    salary: 100000,
    paymentDate: '주간 지급',
    preparation: '정장',
    description: '연말 박람회 기간 스탭 (미래)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 20,
    currentApplicants: 15,
    createdAt: '2024-11-20',
    updatedAt: '2024-11-20',
  },

  // 6. 기간 진행중 (오늘 포함)
  {
    id: 'post-range-ongoing',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[기간-진행중] 추수감사절 프로모션',
    keywords: ['프로모션', '기간', '진행중'],
    date: '2025-11-25~2025-11-30',
    location: '강남 일대',
    time: '10:00 - 20:00',
    salary: 95000,
    paymentDate: '일일 정산',
    preparation: '브랜드 유니폼 제공',
    description: '추수감사절 주간 프로모션 (현재 진행중)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 15,
    currentApplicants: 15,
    createdAt: '2024-11-18',
    updatedAt: '2024-11-18',
  },

  // 7. 기간 완료 (과거 기간)
  {
    id: 'post-range-completed',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'completed',
    title: '[기간-완료] 할로윈 페스티벌 스탭',
    keywords: ['페스티벌', '기간', '완료'],
    date: '2025-10-28~2025-11-03',
    location: '이태원 일대',
    time: '18:00 - 24:00',
    salary: 120000,
    paymentDate: '지급 완료',
    preparation: '페스티벌 복장',
    description: '할로윈 주간 페스티벌 (완료)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 30,
    currentApplicants: 30,
    createdAt: '2024-10-15',
    updatedAt: '2024-11-05',
  },

  // ========== 불연속 날짜 (,) ==========

  // 8. 불연속 예정 (모두 미래)
  {
    id: 'post-multiple-upcoming',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[불연속-예정] 주말 이벤트 스탭',
    keywords: ['이벤트', '주말', '예정'],
    date: '2025-12-07, 2025-12-08, 2025-12-14, 2025-12-15',
    location: '신촌 현대백화점',
    time: '11:00 - 19:00',
    salary: 90000,
    paymentDate: '당일 지급',
    preparation: '편한 복장',
    description: '12월 주말 이벤트 (모두 미래)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 6,
    currentApplicants: 4,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },

  // 9. 불연속 예정 (과거+미래 섞임)
  {
    id: 'post-multiple-upcoming-mixed',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[불연속-예정] 플래시 세일 프로모션',
    keywords: ['프로모션', '세일', '예정'],
    date: '2025-11-20, 2025-11-25, 2025-12-01, 2025-12-05',
    location: '강남 가로수길',
    time: '10:00 - 18:00',
    salary: 85000,
    paymentDate: '당일 지급',
    preparation: '단정한 복장',
    description: '플래시 세일 (과거+미래 날짜 섞임, 미래 남음)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 8,
    currentApplicants: 6,
    createdAt: '2024-11-15',
    updatedAt: '2024-11-15',
  },

  // 10. 불연속 진행중 (오늘 포함, 미래 없음)
  {
    id: 'post-multiple-ongoing',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[불연속-진행중] 특별 프로모션',
    keywords: ['프로모션', '특별', '진행중'],
    date: '2025-11-25, 2025-11-26, 2025-11-28',
    location: '명동 메인거리',
    time: '12:00 - 20:00',
    salary: 100000,
    paymentDate: '당일 지급',
    preparation: '브랜드 유니폼 제공',
    description: '특별 프로모션 (오늘 포함, 미래 없음)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 10,
    currentApplicants: 10,
    createdAt: '2024-11-20',
    updatedAt: '2024-11-20',
  },

  // 11. 불연속 완료 (모두 과거)
  {
    id: 'post-multiple-completed',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'completed',
    title: '[불연속-완료] 블랙프라이데이 세일',
    keywords: ['세일', '블랙프라이데이', '완료'],
    date: '2025-11-22, 2025-11-23, 2025-11-24',
    location: '명동 쇼핑거리',
    time: '09:00 - 22:00',
    salary: 150000,
    paymentDate: '지급 완료',
    preparation: '세일 유니폼 제공',
    description: '블랙프라이데이 주말 세일 (완료)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 25,
    currentApplicants: 25,
    createdAt: '2024-11-10',
    updatedAt: '2024-11-25',
  },

  // ========== 겹치는 스케줄 ==========

  // 12-14. 오늘 같은 시간대 겹침 (당일)
  {
    id: 'post-overlap-1',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침1] 오늘 아침 마라톤 대회',
    keywords: ['마라톤', '행사', '겹침'],
    date: '2025-11-28',
    location: '잠실종합운동장',
    time: '06:00 - 12:00',
    salary: 80000,
    paymentDate: '당일 지급',
    preparation: '편한 운동화, 운동복',
    description: '마라톤 대회 스탭',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 15,
    currentApplicants: 15,
    createdAt: '2024-11-20',
    updatedAt: '2024-11-20',
  },
  {
    id: 'post-overlap-2',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침2] 오늘 아침 자선 행사',
    keywords: ['자선', '행사', '겹침'],
    date: '2025-11-28',
    location: '한강공원',
    time: '07:00 - 13:00',
    salary: 85000,
    paymentDate: '당일 지급',
    preparation: '자선 행사 티셔츠 제공',
    description: '자선 행사 스탭',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 10,
    currentApplicants: 10,
    createdAt: '2024-11-21',
    updatedAt: '2024-11-21',
  },
  {
    id: 'post-overlap-3',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침3] 오늘 오후 박람회',
    keywords: ['박람회', '전시', '겹침'],
    date: '2025-11-28',
    location: 'COEX',
    time: '13:00 - 19:00',
    salary: 90000,
    paymentDate: '당일 지급',
    preparation: '정장 착용',
    description: '박람회 안내 스탭',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 12,
    currentApplicants: 10,
    createdAt: '2024-11-22',
    updatedAt: '2024-11-22',
  },

  // 15-17. 12월 15일 겹침 (기간+불연속+당일)
  {
    id: 'post-overlap-future-1',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침4] 크리스마스 준비 행사',
    keywords: ['크리스마스', '준비', '겹침'],
    date: '2025-12-15',
    location: '명동 거리',
    time: '10:00 - 18:00',
    salary: 100000,
    paymentDate: '당일 지급',
    preparation: '크리스마스 복장',
    description: '크리스마스 준비 행사 (당일)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 20,
    currentApplicants: 15,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },
  {
    id: 'post-overlap-future-2',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침5] 연말 정산 박람회',
    keywords: ['박람회', '연말', '겹침'],
    date: '2025-12-10, 2025-12-15, 2025-12-20',
    location: 'COEX',
    time: '09:00 - 17:00',
    salary: 95000,
    paymentDate: '당일 지급',
    preparation: '정장',
    description: '연말 정산 박람회 (불연속)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 15,
    currentApplicants: 12,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },
  {
    id: 'post-overlap-future-3',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[겹침6] 겨울 축제',
    keywords: ['축제', '겨울', '겹침'],
    date: '2025-12-13~2025-12-17',
    location: '잠실 롯데월드',
    time: '11:00 - 20:00',
    salary: 110000,
    paymentDate: '주간 지급',
    preparation: '축제 유니폼 제공',
    description: '겨울 축제 기간 스탭 (기간)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 25,
    currentApplicants: 20,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },

  // ========== 엣지 케이스 ==========

  // 18. 내일 스케줄 (예정)
  {
    id: 'post-tomorrow',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[내일] 쇼핑몰 오픈 행사',
    keywords: ['오픈', '쇼핑몰', '내일'],
    date: '2025-11-29',
    location: '강남역 지하쇼핑몰',
    time: '10:00 - 18:00',
    salary: 90000,
    paymentDate: '당일 지급',
    preparation: '쇼핑몰 유니폼 제공',
    description: '쇼핑몰 오픈 행사 (내일)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 8,
    currentApplicants: 5,
    createdAt: '2024-11-27',
    updatedAt: '2024-11-27',
  },

  // 19. 한 달 후 (예정)
  {
    id: 'post-next-month',
    authorId: 'manager-1',
    authorName: '김매니저',
    status: 'recruiting',
    title: '[한달후] 신년 행사 준비',
    keywords: ['신년', '행사', '예정'],
    date: '2025-12-28',
    location: '여의도 공원',
    time: '14:00 - 22:00',
    salary: 150000,
    paymentDate: '당일 지급',
    preparation: '신년 행사 복장',
    description: '신년 행사 준비 (한 달 후)',
    managerInfo: { name: '김매니저', phone: '010-1111-1111' },
    recruitCount: 30,
    currentApplicants: 10,
    createdAt: '2024-11-25',
    updatedAt: '2024-11-25',
  },
];

export const mockApplications: Application[] = [
  // ========== post-daily-upcoming (당일 예정) ==========
  {
    id: 'app-1',
    postId: 'post-daily-upcoming',
    applicantId: 'member-1',
    applicantName: '이서연',
    status: 'accepted',
    appliedAt: '2025-11-27',
    message: '이벤트 스탭 경험 3년차입니다. 책임감 있게 임하겠습니다.',
  },
  {
    id: 'app-2',
    postId: 'post-daily-upcoming',
    applicantId: 'member-2',
    applicantName: '김민준',
    status: 'pending',
    appliedAt: '2025-11-27',
    message: '저녁 시간 근무 가능합니다. 열심히 하겠습니다!',
  },
  {
    id: 'app-3',
    postId: 'post-daily-upcoming',
    applicantId: 'member-3',
    applicantName: '박지우',
    status: 'rejected',
    appliedAt: '2025-11-26',
    message: '행사 경험은 없지만 배우고 싶습니다.',
  },

  // ========== post-daily-ongoing (당일 진행중) ==========
  {
    id: 'app-4',
    postId: 'post-daily-ongoing',
    applicantId: 'member-4',
    applicantName: '최서현',
    status: 'accepted',
    appliedAt: '2025-11-26',
    message: '프로모션 스탭 경험 많습니다. 잘 부탁드립니다!',
  },
  {
    id: 'app-5',
    postId: 'post-daily-ongoing',
    applicantId: 'member-5',
    applicantName: '정현우',
    status: 'accepted',
    appliedAt: '2025-11-26',
    message: '신촌 지역 잘 알고 있습니다. 성실히 임하겠습니다.',
  },
  {
    id: 'app-6',
    postId: 'post-daily-ongoing',
    applicantId: 'member-6',
    applicantName: '강지민',
    status: 'accepted',
    appliedAt: '2025-11-25',
    message: '프로모션 행사 다수 참여 경험 있습니다.',
  },

  // ========== post-daily-completed-today (당일 완료) ==========
  {
    id: 'app-7',
    postId: 'post-daily-completed-today',
    applicantId: 'member-7',
    applicantName: '윤서준',
    status: 'accepted',
    appliedAt: '2025-11-27',
    message: '오전 시간 근무 가능합니다. 체력 좋습니다!',
  },
  {
    id: 'app-8',
    postId: 'post-daily-completed-today',
    applicantId: 'member-8',
    applicantName: '임하은',
    status: 'accepted',
    appliedAt: '2025-11-27',
    message: '새벽 집결 가능합니다. 성실히 하겠습니다.',
  },

  // ========== post-range-upcoming (기간 예정) ==========
  {
    id: 'app-9',
    postId: 'post-range-upcoming',
    applicantId: 'member-9',
    applicantName: '조민서',
    status: 'accepted',
    appliedAt: '2025-11-22',
    message: '박람회 경험 다수 있습니다. 기간 내 모든 날짜 근무 가능합니다.',
  },
  {
    id: 'app-10',
    postId: 'post-range-upcoming',
    applicantId: 'member-10',
    applicantName: '한지호',
    status: 'accepted',
    appliedAt: '2025-11-23',
    message: '정장 착용 업무 익숙합니다. 잘 부탁드립니다.',
  },
  {
    id: 'app-11',
    postId: 'post-range-upcoming',
    applicantId: 'member-11',
    applicantName: '배수아',
    status: 'pending',
    appliedAt: '2025-11-24',
    message: '코엑스 인근 거주합니다. 출퇴근 편리합니다.',
  },
  {
    id: 'app-12',
    postId: 'post-range-upcoming',
    applicantId: 'member-12',
    applicantName: '신동현',
    status: 'pending',
    appliedAt: '2025-11-25',
    message: '박람회 스탭 지원합니다. 열심히 하겠습니다!',
  },
  {
    id: 'app-13',
    postId: 'post-range-upcoming',
    applicantId: 'member-13',
    applicantName: '오유진',
    status: 'pending',
    appliedAt: '2025-11-26',
    message: '장기 근무 가능합니다. 성실히 임하겠습니다.',
  },

  // ========== post-range-ongoing (기간 진행중) ==========
  {
    id: 'app-14',
    postId: 'post-range-ongoing',
    applicantId: 'member-14',
    applicantName: '송지아',
    status: 'accepted',
    appliedAt: '2025-11-20',
    message: '프로모션 업무 경험 풍부합니다. 열심히 하겠습니다!',
  },
  {
    id: 'app-15',
    postId: 'post-range-ongoing',
    applicantId: 'member-15',
    applicantName: '홍민재',
    status: 'accepted',
    appliedAt: '2025-11-21',
    message: '강남 지역 근무 경험 많습니다.',
  },
  {
    id: 'app-16',
    postId: 'post-range-ongoing',
    applicantId: 'member-16',
    applicantName: '류서윤',
    status: 'accepted',
    appliedAt: '2025-11-22',
    message: '추수감사절 기간 근무 가능합니다. 잘 부탁드립니다.',
  },

  // ========== post-multiple-upcoming (불연속 예정) ==========
  {
    id: 'app-17',
    postId: 'post-multiple-upcoming',
    applicantId: 'member-17',
    applicantName: '안지훈',
    status: 'pending',
    appliedAt: '2025-11-26',
    message: '주말 근무 선호합니다. 이벤트 스탭 경험 있습니다.',
  },
  {
    id: 'app-18',
    postId: 'post-multiple-upcoming',
    applicantId: 'member-18',
    applicantName: '권나연',
    status: 'pending',
    appliedAt: '2025-11-27',
    message: '신촌 인근 거주합니다. 주말 모두 근무 가능합니다.',
  },
  {
    id: 'app-19',
    postId: 'post-multiple-upcoming',
    applicantId: 'member-19',
    applicantName: '전민호',
    status: 'accepted',
    appliedAt: '2025-11-25',
    message: '백화점 이벤트 다수 참여했습니다. 성실히 임하겠습니다.',
  },

  // ========== post-multiple-ongoing-mixed (불연속 진행중) ==========
  {
    id: 'app-20',
    postId: 'post-multiple-ongoing-mixed',
    applicantId: 'member-20',
    applicantName: '노서연',
    status: 'accepted',
    appliedAt: '2025-11-18',
    message: '플래시 세일 경험 있습니다. 열심히 하겠습니다!',
  },
  {
    id: 'app-21',
    postId: 'post-multiple-ongoing-mixed',
    applicantId: 'member-21',
    applicantName: '하준서',
    status: 'accepted',
    appliedAt: '2025-11-19',
    message: '강남 가로수길 잘 알고 있습니다.',
  },
  {
    id: 'app-22',
    postId: 'post-multiple-ongoing-mixed',
    applicantId: 'member-22',
    applicantName: '문채원',
    status: 'pending',
    appliedAt: '2025-11-27',
    message: '남은 날짜 모두 근무 가능합니다. 지원합니다!',
  },

  // ========== post-overlap-1 (겹침1) ==========
  {
    id: 'app-23',
    postId: 'post-overlap-1',
    applicantId: 'member-23',
    applicantName: '표지원',
    status: 'accepted',
    appliedAt: '2025-11-22',
    message: '마라톤 대회 스탭 경험 있습니다. 체력 좋습니다!',
  },
  {
    id: 'app-24',
    postId: 'post-overlap-1',
    applicantId: 'member-24',
    applicantName: '서민준',
    status: 'accepted',
    appliedAt: '2025-11-23',
    message: '새벽 집결 가능합니다. 열심히 하겠습니다.',
  },

  // ========== post-overlap-2 (겹침2) ==========
  {
    id: 'app-25',
    postId: 'post-overlap-2',
    applicantId: 'member-25',
    applicantName: '양서현',
    status: 'accepted',
    appliedAt: '2025-11-23',
    message: '자선 행사 참여 경험 많습니다. 성실히 임하겠습니다.',
  },
  {
    id: 'app-26',
    postId: 'post-overlap-2',
    applicantId: 'member-26',
    applicantName: '황지우',
    status: 'accepted',
    appliedAt: '2025-11-24',
    message: '한강공원 인근 거주합니다. 아침 시간 근무 가능합니다.',
  },

  // ========== post-overlap-3 (겹침3) ==========
  {
    id: 'app-27',
    postId: 'post-overlap-3',
    applicantId: 'member-27',
    applicantName: '차예은',
    status: 'accepted',
    appliedAt: '2025-11-24',
    message: 'COEX 박람회 스탭 경험 있습니다. 잘 부탁드립니다.',
  },
  {
    id: 'app-28',
    postId: 'post-overlap-3',
    applicantId: 'member-28',
    applicantName: '진현우',
    status: 'pending',
    appliedAt: '2025-11-26',
    message: '오후 시간 근무 가능합니다. 열심히 하겠습니다!',
  },

  // ========== post-overlap-future-1 (겹침4) ==========
  {
    id: 'app-29',
    postId: 'post-overlap-future-1',
    applicantId: 'member-29',
    applicantName: '목지민',
    status: 'accepted',
    appliedAt: '2025-11-26',
    message: '크리스마스 행사 경험 있습니다. 성실히 임하겠습니다.',
  },
  {
    id: 'app-30',
    postId: 'post-overlap-future-1',
    applicantId: 'member-30',
    applicantName: '탁서준',
    status: 'pending',
    appliedAt: '2025-11-27',
    message: '명동 지역 잘 알고 있습니다. 열심히 하겠습니다!',
  },
  {
    id: 'app-31',
    postId: 'post-overlap-future-1',
    applicantId: 'member-31',
    applicantName: '편하은',
    status: 'pending',
    appliedAt: '2025-11-27',
    message: '크리스마스 준비 행사 참여하고 싶습니다.',
  },

  // ========== post-tomorrow (내일) ==========
  {
    id: 'app-32',
    postId: 'post-tomorrow',
    applicantId: 'member-32',
    applicantName: '소민서',
    status: 'accepted',
    appliedAt: '2025-11-27',
    message: '강남역 인근 거주합니다. 내일 근무 가능합니다!',
  },
  {
    id: 'app-33',
    postId: 'post-tomorrow',
    applicantId: 'member-33',
    applicantName: '석지호',
    status: 'pending',
    appliedAt: '2025-11-27',
    message: '쇼핑몰 오픈 행사 경험 있습니다. 잘 부탁드립니다.',
  },
  {
    id: 'app-34',
    postId: 'post-tomorrow',
    applicantId: 'member-34',
    applicantName: '방수아',
    status: 'pending',
    appliedAt: '2025-11-28',
    message: '내일 하루 근무 가능합니다. 열심히 하겠습니다!',
  },

  // ========== post-next-month (한달후) ==========
  {
    id: 'app-35',
    postId: 'post-next-month',
    applicantId: 'member-35',
    applicantName: '우동현',
    status: 'pending',
    appliedAt: '2025-11-26',
    message: '신년 행사 참여하고 싶습니다. 성실히 임하겠습니다.',
  },
  {
    id: 'app-36',
    postId: 'post-next-month',
    applicantId: 'member-36',
    applicantName: '변유진',
    status: 'pending',
    appliedAt: '2025-11-27',
    message: '여의도 인근 거주합니다. 저녁 시간 근무 가능합니다.',
  },
  {
    id: 'app-37',
    postId: 'post-next-month',
    applicantId: 'member-37',
    applicantName: '좌지아',
    status: 'rejected',
    appliedAt: '2025-11-25',
    message: '신년 행사 경험은 없지만 배우고 싶습니다.',
  },

  // ========== 추가 대기중 지원자들 ==========
  {
    id: 'app-38',
    postId: 'post-range-upcoming',
    applicantId: 'member-38',
    applicantName: '구민재',
    status: 'pending',
    appliedAt: '2025-11-28',
    message: '박람회 스탭 지원합니다. 12월 15-20일 모두 가능합니다.',
  },
  {
    id: 'app-39',
    postId: 'post-range-upcoming',
    applicantId: 'member-39',
    applicantName: '옹서윤',
    status: 'pending',
    appliedAt: '2025-11-28',
    message: '연말 박람회 참여 희망합니다. 성실히 임하겠습니다.',
  },
  {
    id: 'app-40',
    postId: 'post-overlap-future-1',
    applicantId: 'member-40',
    applicantName: '국지훈',
    status: 'pending',
    appliedAt: '2025-11-28',
    message: '크리스마스 시즌 행사 경험 많습니다. 잘 부탁드립니다!',
  },
];

export const mockAttendanceReviews: AttendanceReview[] = [
  {
    id: 'rev-1',
    postId: 'post-daily-completed-past',
    userId: 'member-1',
    score: 95,
    comment:
      '시간 준수 완벽하고 업무 처리 능력이 뛰어남. 다음에도 함께 하고 싶습니다.',
    reviewedBy: 'manager-1',
    createdAt: '2025-11-28',
  },
  {
    id: 'rev-2',
    postId: 'post-daily-completed-past',
    userId: 'member-2',
    score: 88,
    comment: '성실하게 근무했으나 업무 숙지에 약간 시간이 필요했습니다.',
    reviewedBy: 'manager-1',
    createdAt: '2025-11-28',
  },
  {
    id: 'rev-3',
    postId: 'post-range-completed',
    userId: 'member-3',
    score: 92,
    comment: '페스티벌 기간 동안 성실히 근무했습니다. 고객 응대가 좋았습니다.',
    reviewedBy: 'manager-1',
    createdAt: '2025-11-05',
  },
  {
    id: 'rev-4',
    postId: 'post-range-completed',
    userId: 'member-4',
    score: 85,
    comment: '전반적으로 양호하나 시간 준수에 개선이 필요합니다.',
    reviewedBy: 'manager-1',
    createdAt: '2025-11-05',
  },
  {
    id: 'rev-5',
    postId: 'post-multiple-completed',
    userId: 'member-5',
    score: 98,
    comment: '블랙프라이데이 기간 동안 완벽한 근무 태도를 보였습니다. 최고!',
    reviewedBy: 'manager-1',
    createdAt: '2025-11-25',
  },
];

export const mockSchedules: Schedule[] = [
  // member-1의 스케줄
  {
    id: 'schedule-1',
    userId: 'member-1',
    postId: 'post-daily-upcoming',
    title: '[당일-예정] 저녁 이벤트 스탭',
    date: '2025-11-28',
    salary: 100000,
    paid: false,
  },
  {
    id: 'schedule-2',
    userId: 'member-4',
    postId: 'post-daily-ongoing',
    title: '[당일-진행중] 오후 프로모션 스탭',
    date: '2025-11-28',
    salary: 90000,
    paid: false,
  },
  {
    id: 'schedule-3',
    userId: 'member-7',
    postId: 'post-daily-completed-today',
    title: '[당일-완료] 오전 행사 스탭',
    date: '2025-11-28',
    salary: 80000,
    paid: true,
  },
  {
    id: 'schedule-4',
    userId: 'member-9',
    postId: 'post-range-upcoming',
    title: '[기간-예정] 연말 박람회 스탭',
    date: '2025-12-15~2025-12-20',
    salary: 100000,
    paid: false,
  },
  {
    id: 'schedule-5',
    userId: 'member-14',
    postId: 'post-range-ongoing',
    title: '[기간-진행중] 추수감사절 프로모션',
    date: '2025-11-25~2025-11-30',
    salary: 95000,
    paid: false,
  },
];
